# This Makefile is generated by the made script:
# https://github.com/alx741/made
#
# Replace FILE with your filename
#
# Dependencies:
# 	Pandoc


FILE=post

all: $(FILE).html code.hex

$(FILE).html: $(FILE).md
	pandoc $< -o $@

code.hex: code.asm
	gpasm $< -o $@

clean:
	rm $(FILE).html code.lst code.cod code.hex
